# this workflow should happen on staging branch!!!
name: Build, deploy, and trigger UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
  deploy-render:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.SERVICE_ID }}
          api_key: ${{ secrets.RENDER_TOKEN }}
          wait_deploy: true
  trigger-ui-tests:
    needs: deploy-render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger UI tests workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/svetlilaloli/Library-ui-test/dispatches \
            -d '{"event_type": "trigger-ui-tests"}'
